import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'gestor-component',
  templateUrl: './gestor-component.component.html',
  styleUrls: ['./gestor-component.component.css']
})
export class GestorComponentComponent implements OnInit {
  verLogin:boolean=true;
  verCrearPasajero=false;
  verCrearVuelo=false;
  verCrearTripu=false;
  verReserva=false;
  verReporteVuelo=false;
  verConsultarVuelos=false;
  verConsultarAerolineas=false;
  verConsultarAviones=false;
  verPasajerosVuelo =false;
  verDestinos=false;
  constructor() { }

  ngOnInit(): void {
  }

  OnVerCrearPasajero(){
    this.verLogin=false;
    this.verCrearVuelo=false;
    this.verCrearPasajero=true;
    this.verReserva=false;
    this.verCrearTripu=false;
    this.verReporteVuelo=false;
    this.verConsultarVuelos=false;
    this.verConsultarAerolineas=false;
    this.verConsultarAviones=false;
    this.verPasajerosVuelo=false;
    this.verDestinos=false;
  }
  OnVerCrearVuelo(){
    this.verLogin=false;
    this.verCrearPasajero=false;
    this.verCrearVuelo=true;
    this.verReserva=false;
    this.verCrearTripu=false;
    this.verReporteVuelo=false;
    this.verConsultarVuelos=false;
    this.verConsultarAerolineas=false;
    this.verConsultarAviones=false;
    this.verPasajerosVuelo=false;
    this.verDestinos=false;
  }
  OnVerReserva(){
    this.verReserva=true;
    this.verLogin=false;
    this.verCrearPasajero=false;
    this.verCrearVuelo=false;
    this.verCrearTripu=false;
    this.verReporteVuelo=false;
    this.verConsultarVuelos=false;
    this.verConsultarAerolineas=false;
    this.verConsultarAviones=false;
    this.verPasajerosVuelo=false;
    this.verDestinos=false;
  }
  OnVerCrearTripu(){
    this.verReserva=false;
    this.verLogin=false;
    this.verCrearPasajero=false;
    this.verCrearVuelo=false;
    this.verCrearTripu=true;
    this.verReporteVuelo=false;
    this.verConsultarVuelos=false;
    this.verConsultarAerolineas=false;
    this.verConsultarAviones=false;
    this.verPasajerosVuelo=false;
    this.verDestinos=false;
  }
  OnVerReporteVuelo(){
    this.verReserva=false;
    this.verLogin=false;
    this.verCrearPasajero=false;
    this.verCrearVuelo=false;
    this.verCrearTripu=false;
    this.verReporteVuelo=true;
    this.verConsultarVuelos=false;
    this.verConsultarAerolineas=false;
    this.verConsultarAviones=false;
    this.verPasajerosVuelo=false;
    this.verDestinos=false;
  }
  OnVerConsultarVuelos(){
    this.verReserva=false;
    this.verLogin=false;
    this.verCrearPasajero=false;
    this.verCrearVuelo=false;
    this.verCrearTripu=false;
    this.verReporteVuelo=false;
    this.verConsultarVuelos=true;
    this.verConsultarAerolineas=false;
    this.verConsultarAviones=false;
    this.verPasajerosVuelo=false;
    this.verDestinos=false;
  }
  OnVerConsultarAerolineas(){
    this.verReserva=false;
    this.verLogin=false;
    this.verCrearPasajero=false;
    this.verCrearVuelo=false;
    this.verCrearTripu=false;
    this.verReporteVuelo=false;
    this.verConsultarVuelos=false;
    this.verConsultarAerolineas=true;
    this.verConsultarAviones=false;
    this.verPasajerosVuelo=false;
    this.verDestinos=false;
  }
  OnVerConsultarAviones(){
    this.verReserva=false;
    this.verLogin=false;
    this.verCrearPasajero=false;
    this.verCrearVuelo=false;
    this.verCrearTripu=false;
    this.verReporteVuelo=false;
    this.verConsultarVuelos=false;
    this.verConsultarAerolineas=false;
    this.verConsultarAviones=true;
    this.verPasajerosVuelo=false;
    this.verDestinos=false;
  }
  OnVerConsultarPasajerosVuelo(){
    this.verReserva=false;
    this.verLogin=false;
    this.verCrearPasajero=false;
    this.verCrearVuelo=false;
    this.verCrearTripu=false;
    this.verReporteVuelo=false;
    this.verConsultarVuelos=false;
    this.verConsultarAerolineas=false;
    this.verConsultarAviones=false;
    this.verPasajerosVuelo=true;
    this.verDestinos=false;

  }
  onVerDestinos(){
    this.verReserva=false;
    this.verLogin=false;
    this.verCrearPasajero=false;
    this.verCrearVuelo=false;
    this.verCrearTripu=false;
    this.verReporteVuelo=false;
    this.verConsultarVuelos=false;
    this.verConsultarAerolineas=false;
    this.verConsultarAviones=false;
    this.verPasajerosVuelo=false;
    this.verDestinos=true;

  }
}
