package com.gt.umg.ing.software.models.entity;
// Generated 17/03/2022 09:17:45 PM by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Aeropuerto generated by hbm2java
 */
@Entity
@Table(name = "aeropuerto",
        schema = "public"
)
public class Aeropuerto implements java.io.Serializable {

    private int idAeropuerto;
    private String nombre;
    private String pais;
    private String ciudad;
    private List<Aerolinea> aerolineas;

    public Aeropuerto() {
    }

    public Aeropuerto(int idAeropuerto) {
        this.idAeropuerto = idAeropuerto;
    }

    public Aeropuerto(int idAeropuerto, String nombre, String pais, String ciudad, List<Aerolinea> aerolineas) {
        this.idAeropuerto = idAeropuerto;
        this.nombre = nombre;
        this.pais = pais;
        this.ciudad = ciudad;
        this.aerolineas = aerolineas;
    }

    @Id

    @Column(name = "id_aeropuerto", unique = true, nullable = false)
    public int getIdAeropuerto() {
        return this.idAeropuerto;
    }

    public void setIdAeropuerto(int idAeropuerto) {
        this.idAeropuerto = idAeropuerto;
    }

    @Column(name = "nombre", length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "pais", length = 45)
    public String getPais() {
        return this.pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    @Column(name = "ciudad", length = 45)
    public String getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "aeropuerto_aerolinea", schema = "public",
            joinColumns = {
                @JoinColumn(name = "id_aeropuerto", nullable = false, updatable = false)},
            inverseJoinColumns = {
                @JoinColumn(name = "id_aerolinea", nullable = false, updatable = false)})
    public List<Aerolinea> getAerolineas() {
        return this.aerolineas;
    }

    public void setAerolineas(List<Aerolinea> aerolineas) {
        this.aerolineas = aerolineas;
    }
}
