package com.gt.umg.ing.software.models.entity;
// Generated 17/03/2022 09:17:45 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Aerolinea generated by hbm2java
 */
@Entity
@Table(name = "aerolinea",
        schema = "public"
)
public class Aerolinea implements java.io.Serializable {

    private int id_aerolinea;
    private String nombre;
    private List<Aeropuerto> aeropuertos;
    private List<Avion> avions;
//    private List<AeropuertoAerolineaId> aeropuertos;

    public Aerolinea() {
    }

    public Aerolinea(int id_aerolinea) {
        this.id_aerolinea = id_aerolinea;
    }

    public Aerolinea(String nombre, List<Avion> avions) {
        this.nombre = nombre;
        this.avions = avions;
    }

    public Aerolinea(String nombre, List<Avion> avions, List<Aeropuerto> aeropuertos) {
        this.nombre = nombre;
        this.avions = avions;
        this.aeropuertos = aeropuertos;
    }

    @Id
    @Column(name = "id_aerolinea", unique = true, nullable = false)
    public int getIdAerolinea() {
        return this.id_aerolinea;
    }

    public void setIdAerolinea(int id_aerolinea) {
        this.id_aerolinea = id_aerolinea;
    }

    @Column(name = "nombre", length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @JsonIgnoreProperties("aerolineas")
    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "aerolineas")
    public List<Aeropuerto> getAeropuertos() {
        return this.aeropuertos;
    }

    public void setAeropuertos(List<Aeropuerto> aeropuertos) {
        this.aeropuertos = aeropuertos;
    }

    @JsonIgnoreProperties("aerolinea")
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "aerolinea", cascade = CascadeType.ALL, orphanRemoval = true)
    public List<Avion> getAvions() {
        return this.avions;
    }

    public void setAvions(List<Avion> avions) {
        this.avions = avions;
    }

}
