/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gt.umg.ing.software.models.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AvionId generated by hbm2java
 */
@Embeddable
public class AvionId implements java.io.Serializable {

    private int idAvion;
    private int idAerolinea;

    public AvionId() {
    }

    public AvionId(int idAvion, int idAerolinea) {
        this.idAvion = idAvion;
        this.idAerolinea = idAerolinea;
    }

    @Column(name = "id_avion", nullable = false)
    public int getIdAvion() {
        return this.idAvion;
    }

    public void setIdAvion(int idAvion) {
        this.idAvion = idAvion;
    }

    @Column(name = "id_aerolinea", nullable = false)
    public int getIdAerolinea() {
        return this.idAerolinea;
    }

    public void setIdAerolinea(int idAerolinea) {
        this.idAerolinea = idAerolinea;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof AvionId)) {
            return false;
        }
        AvionId castOther = (AvionId) other;

        return (this.getIdAvion() == castOther.getIdAvion())
                && (this.getIdAerolinea() == castOther.getIdAerolinea());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdAvion();
        result = 37 * result + this.getIdAerolinea();
        return result;
    }

}
