package com.gt.umg.ing.software.models.entity;
// Generated 17/03/2022 09:17:45 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Avion generated by hbm2java
 */
@Entity
@Table(name = "avion",
         schema = "public"
)
public class Avion implements java.io.Serializable {

    private int id_avion;
     private Aerolinea aerolinea;
//    private int aerolinea;
    private String modelo;
    private String marca;
    private String anio;
//     private Set vuelos = new HashSet(0);

    public Avion() {
    }

    public Avion(int id_avion, Aerolinea aerolinea) {
        this.id_avion = id_avion;
        this.aerolinea = aerolinea;
    }

    public Avion(int id_avion, Aerolinea aerolinea, String modelo, String marca, String anio) {
        this.id_avion = id_avion;
        this.aerolinea = aerolinea;
        this.modelo = modelo;
        this.marca = marca;
        this.anio = anio;
//       this.vuelos = vuelos;
    }

    @Id
    @Column(name = "id_avion", unique = true, nullable = false)
    public int getIdAvion() {
        return this.id_avion;
    }

    public void setIdAvion(int id_avion) {
        this.id_avion = id_avion;
    }

    @ManyToOne()
    @JoinColumn(name = "id_aerolinea", nullable = false)
    public Aerolinea getAerolinea() {
        return this.aerolinea;
    }

    public void setAerolinea(Aerolinea aerolinea) {
        this.aerolinea = aerolinea;
    }

    @Column(name = "modelo", length = 45)
    public String getModelo() {
        return this.modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    @Column(name = "marca", length = 30)
    public String getMarca() {
        return this.marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    @Column(name = "anio", length = 4)
    public String getAnio() {
        return this.anio;
    }

    public void setAnio(String anio) {
        this.anio = anio;
    }

//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "avion")
//    public Set getVuelos() {
//        return this.vuelos;
//    }
//
//    public void setVuelos(Set vuelos) {
//        this.vuelos = vuelos;
//    }

}
