/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gt.umg.ing.software.models.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatalogoAvion generated by hbm2java
 */
@Entity
@Table(name = "catalogo_avion",
        schema = "public"
)
public class CatalogoAvion implements java.io.Serializable {

    private int idAvion;
    private String modelo;
    private String marca;
    private List<Avion> avions;
//    private List<Sillon> sillons;

    public CatalogoAvion() {
    }

    public CatalogoAvion(int idAvion) {
        this.idAvion = idAvion;
    }

    public CatalogoAvion(int idAvion, String modelo, String marca, List<Avion> avions, List<Sillon> sillons) {
        this.idAvion = idAvion;
        this.modelo = modelo;
        this.marca = marca;
        this.avions = avions;
//        this.sillons = sillons;
    }

    @Id
    @Column(name = "id_avion", unique = true, nullable = false)
    public int getIdAvion() {
        return this.idAvion;
    }

    public void setIdAvion(int idAvion) {
        this.idAvion = idAvion;
    }

    @Column(name = "modelo", length = 45)
    public String getModelo() {
        return this.modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    @Column(name = "marca", length = 45)
    public String getMarca() {
        return this.marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogoAvion")
    public List<Avion> getAvions() {
        return this.avions;
    }

    public void setAvions(List<Avion> avions) {
        this.avions = avions;
    }

//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogoAvion")
//    public List<Sillon> getSillons() {
//        return this.sillons;
//    }
//
//    public void setSillons(List<Sillon> sillons) {
//        this.sillons = sillons;
//    }

}
