package com.gt.umg.ing.software.models.entity;
// Generated 17/03/2022 09:17:45 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pasajero generated by hbm2java
 */
@Entity
@Table(name = "pasajero",
         schema = "public"
)
public class Pasajero implements java.io.Serializable {

    private Long no_pasaporte;
    private String nombre;
    private Date fecha_nacimiento;
    private String pais_nacimiento;
    private String correo_electronico;
    private Integer codigoAera;
    private Integer numero_telefono;
    private Integer numero_emergencia;
    private String direccion;
    private List<VueloPasajero> vueloPasajeros;

    public Pasajero() {
    }

    public Pasajero(Long no_pasaporte) {
        this.no_pasaporte = no_pasaporte;
    }

    public Pasajero(Long no_pasaporte, String nombre, Date fecha_nacimiento, String pais_nacimiento, String correo_electronico, Integer numero_telefono, Integer numero_emergencia, String direccion, Integer codigoAera, List<VueloPasajero> detalleVuelos) {
        this.no_pasaporte = no_pasaporte;
        this.nombre = nombre;
        this.fecha_nacimiento = fecha_nacimiento;
        this.pais_nacimiento = pais_nacimiento;
        this.correo_electronico = correo_electronico;
        this.numero_telefono = numero_telefono;
        this.numero_emergencia = numero_emergencia;
        this.codigoAera = codigoAera;
        this.direccion = direccion;
        this.vueloPasajeros = detalleVuelos;
    }

    @Id

    @Column(name = "no_pasaporte", unique = true, nullable = false)
    public Long getNoPasaporte() {
        return this.no_pasaporte;
    }

    public void setNoPasaporte(Long no_pasaporte) {
        this.no_pasaporte = no_pasaporte;
    }

    @Column(name = "nombre", length = 60)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_nacimiento", length = 13)
    public Date getFechaNacimiento() {
        return this.fecha_nacimiento;
    }

    public void setFechaNacimiento(Date fecha_nacimiento) {
        this.fecha_nacimiento = fecha_nacimiento;
    }

    @Column(name = "pais_nacimiento", length = 45)
    public String getPaisNacimiento() {
        return this.pais_nacimiento;
    }

    public void setPaisNacimiento(String pais_nacimiento) {
        this.pais_nacimiento = pais_nacimiento;
    }

    @Column(name = "correo_electronico", length = 30)
    public String getCorreoElectronico() {
        return this.correo_electronico;
    }

    public void setCorreoElectronico(String correo_electronico) {
        this.correo_electronico = correo_electronico;
    }

    @Column(name = "numero_telefono")
    public Integer getNumeroTelefono() {
        return this.numero_telefono;
    }

    public void setNumeroTelefono(Integer numero_telefono) {
        this.numero_telefono = numero_telefono;
    }

    @Column(name = "numero_emergencia")
    public Integer getNumeroEmergencia() {
        return this.numero_emergencia;
    }

    public void setNumeroEmergencia(Integer numero_emergencia) {
        this.numero_emergencia = numero_emergencia;
    }

    @Column(name = "direccion", length = 100)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "codigo_aera")
    public Integer getCodigoAera() {
        return this.codigoAera;
    }

    public void setCodigoAera(Integer codigoAera) {
        this.codigoAera = codigoAera;
    }

    @JsonIgnore()
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pasajero")
    public List<VueloPasajero> getVueloPasajeros() {
        return this.vueloPasajeros;
    }

    public void setVueloPasajeros(List<VueloPasajero> vueloPasajeros) {
        this.vueloPasajeros = vueloPasajeros;
    }

}
