package com.gt.umg.ing.software.models.entity;
// Generated 21/03/2022 10:43:13 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol",
         schema = "public"
)
public class Rol implements java.io.Serializable {

    private int idRol;
    private String nombre;
    private List<Usuario> usuarios;

    public Rol() {
    }

    public Rol(int idRol) {
        this.idRol = idRol;
    }

    public Rol(int idRol, String nombre, List<Usuario> usuarios) {
        this.idRol = idRol;
        this.nombre = nombre;
        this.usuarios = usuarios;
    }

    @Id

    @Column(name = "id_rol", unique = true, nullable = false)
    public int getIdRol() {
        return this.idRol;
    }

    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }

    @Column(name = "nombre", length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @JsonIgnore()
    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
    public List<Usuario> getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(List<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

}
