package com.gt.umg.ing.software.models.entity;

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sillon generated by hbm2java
 */
@Entity
@Table(name = "sillon",
        schema = "public"
)
public class Sillon implements java.io.Serializable {

    private int idSillon;
    private int avion;
    private String nombre;
//    private List<VueloPasajero> vueloPasajeros ;

    public Sillon() {
    }

    public Sillon(int idSillon, int avion) {
        this.idSillon = idSillon;
        this.avion = avion;
    }

    public Sillon(int idSillon, int avion, String nombre, List<VueloPasajero> vueloPasajeros) {
        this.idSillon = idSillon;
        this.avion = avion;
        this.nombre = nombre;
//        this.vueloPasajeros = vueloPasajeros;
    }

    @Id

    @Column(name = "id_sillon", unique = true, nullable = false)
    public int getIdSillon() {
        return this.idSillon;
    }

    public void setIdSillon(int idSillon) {
        this.idSillon = idSillon;
    }

//    @ManyToOne()
    @Column(name = "id_avion", nullable = false)
    public int getAvion() {
        return this.avion;
    }

    public void setAvion(int avion) {
        this.avion = avion;
    }

    @Column(name = "nombre", length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sillon")
//    public List<VueloPasajero> getVueloPasajeros() {
//        return this.vueloPasajeros;
//    }
//
//    public void setVueloPasajeros(List<VueloPasajero> vueloPasajeros) {
//        this.vueloPasajeros = vueloPasajeros;
//    }
}
