package com.gt.umg.ing.software.models.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sillon generated by hbm2java
 */
@Entity
@Table(name = "sillon",
         schema = "public"
)
public class Sillon implements java.io.Serializable {

    private int idSillon;
    private int catalogoAvion;
    private String nombre;

    public Sillon() {
    }

    public Sillon(int idSillon, int catalogoAvion) {
        this.idSillon = idSillon;
        this.catalogoAvion = catalogoAvion;
    }

    public Sillon(int idSillon, int catalogoAvion, String nombre) {
        this.idSillon = idSillon;
        this.catalogoAvion = catalogoAvion;
        this.nombre = nombre;
    }

    @Id

    @Column(name = "id_sillon", unique = true, nullable = false)
    public int getIdSillon() {
        return this.idSillon;
    }

    public void setIdSillon(int idSillon) {
        this.idSillon = idSillon;
    }

//    @ManyToOne(fetch = FetchType.LAZY)
    @Column(name = "id_avion", nullable = false)
    public int getCatalogoAvion() {
        return this.catalogoAvion;
    }

    public void setCatalogoAvion(int catalogoAvion) {
        this.catalogoAvion = catalogoAvion;
    }

    @Column(name = "nombre", length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
