package com.gt.umg.ing.software.models.entity;
// Generated 17/03/2022 09:17:45 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tripulante generated by hbm2java
 */
@Entity
@Table(name = "tripulante",
         schema = "public"
)
public class Tripulante implements java.io.Serializable {

    private int id;
    private String nombre;
    private String puesto;
    private Character estado;
    private List<Vuelo> detalleVuelos;

    public Tripulante() {
    }

    public Tripulante(int id) {
        this.id = id;
    }

    public Tripulante(int id, String nombre, String puesto, Character estado, List<Vuelo> detalleVuelos) {
        this.id = id;
        this.nombre = nombre;
        this.puesto = puesto;
        this.estado = estado;
        this.detalleVuelos = detalleVuelos;
    }

    @Id
    @Column(name = "id_tripulante", unique = true, nullable = false)
    public int getIdTripulante() {
        return this.id;
    }

    public void setIdTripulante(int idTripulante) {
        this.id = idTripulante;
    }

    @Column(name = "nombre", length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "puesto", length = 45)
    public String getPuesto() {
        return this.puesto;
    }

    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }

    @Column(name = "estado", length = 1)
    public Character getEstado() {
        return this.estado;
    }

    public void setEstado(Character estado) {
        this.estado = estado;
    }

    @JsonIgnore()
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tripulantes")
    public List<Vuelo> getDetalleVuelos() {
        return this.detalleVuelos;
    }

    public void setDetalleVuelos(List<Vuelo> detalleVuelos) {
        this.detalleVuelos = detalleVuelos;
    }

}
