package com.gt.umg.ing.software.models.entity;
// Generated 21/03/2022 10:43:13 AM by Hibernate Tools 4.3.1


import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VueloPasajeroId generated by hbm2java
 */
@Embeddable
public class VueloPasajeroId  implements java.io.Serializable {


     private int idVuelo;
     private long noPasaporte;

    public VueloPasajeroId() {
    }

    public VueloPasajeroId(int idVuelo, Long noPasaporte) {
       this.idVuelo = idVuelo;
       this.noPasaporte = noPasaporte;
    }
   


    @Column(name="id_vuelo", nullable=false)
    public int getIdVuelo() {
        return this.idVuelo;
    }
    
    public void setIdVuelo(int idVuelo) {
        this.idVuelo = idVuelo;
    }


    @Column(name="no_pasaporte", nullable=false)
    public long getNoPasaporte() {
        return this.noPasaporte;
    }
    
    public void setNoPasaporte(long noPasaporte) {
        this.noPasaporte = noPasaporte;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VueloPasajeroId) ) return false;
		 VueloPasajeroId castOther = ( VueloPasajeroId ) other; 
         
		 return (this.getIdVuelo()==castOther.getIdVuelo())
 && (this.getNoPasaporte()==castOther.getNoPasaporte());
   }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 97 * hash + this.idVuelo;
        hash = 97 * hash + Objects.hashCode(this.noPasaporte);
        return hash;
    }
   


}


