package com.gt.umg.ing.software.models.entity;
// Generated 17/03/2022 09:17:45 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vuelo generated by hbm2java
 */
@Entity
@Table(name = "vuelo",
        schema = "public"
)
public class Vuelo implements java.io.Serializable {

    private int id_vuelo;
//     private Aeropuerto aeropuertoByAeropuertoLlegada;
//     private Aeropuerto aeropuertoByAeropuertoSalida;
    private int aeropuertoLlegada;
    private int aeropuertoSalida;
//    private Avion avion;
    private int avion;
    private Date fechaHoraSalida;
    private Date fechaHoraLlegada;
    private String estado;
    private BigDecimal precioEconomica;
    private BigDecimal precioEjecutiva;
    private List<Tripulante> tripulantes;
    private List<VueloPasajero> vueloPasajeros;

    public Vuelo() {
    }

    public Vuelo(int id_vuelo, int aeropuertoByAeropuertoLlegada, int aeropuertoByAeropuertoSalida, int avion) {
        this.id_vuelo = id_vuelo;
        this.aeropuertoLlegada = aeropuertoByAeropuertoLlegada;
        this.aeropuertoSalida = aeropuertoByAeropuertoSalida;
        this.avion = avion;
    }

    public Vuelo(int id_vuelo, int aeropuertoByAeropuertoLlegada, int aeropuertoByAeropuertoSalida, int avion, Date fechaHoraSalida, Date fechaHoraLlegada, String estado, Set detalleVuelos, BigDecimal precioEconomica, BigDecimal precioEjecutiva, List<Tripulante> tripulantes, List<VueloPasajero> vueloPasajeros) {
        this.id_vuelo = id_vuelo;
        this.aeropuertoLlegada = aeropuertoByAeropuertoLlegada;
        this.aeropuertoSalida = aeropuertoByAeropuertoSalida;
        this.avion = avion;
        this.fechaHoraSalida = fechaHoraSalida;
        this.fechaHoraLlegada = fechaHoraLlegada;
        this.estado = estado;
        this.precioEconomica = precioEconomica;
        this.precioEjecutiva = precioEjecutiva;
        this.tripulantes = tripulantes;
        this.vueloPasajeros = vueloPasajeros;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_vuelo", unique = true, nullable = false)
    public int getIdvuelo() {
        return this.id_vuelo;
    }

    public void setIdvuelo(int id_vuelo) {
        this.id_vuelo = id_vuelo;
    }

//    @ManyToOne(fetch = FetchType.LAZY)
    @Column(name = "aeropuerto_llegada", nullable = false)
    public int getAeropuertoLlegada() {
        return this.aeropuertoLlegada;
    }

    public void setAeropuertoLlegada(int aeropuertoLlegada) {
        this.aeropuertoLlegada = aeropuertoLlegada;
    }

//    @ManyToOne(fetch = FetchType.LAZY)
    @Column(name = "aeropuerto_salida", nullable = false)
    public int getAeropuertoSalida() {
        return this.aeropuertoSalida;
    }

    public void setAeropuertoSalida(int aeropuertoSalida) {
        this.aeropuertoSalida = aeropuertoSalida;
    }

//    @ManyToOne(fetch = FetchType.LAZY)
    @Column(name = "id_avion", nullable = false)
    public int getAvion() {
        return this.avion;
    }

    public void setAvion(int avion) {
        this.avion = avion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_hora_salida", length = 29)
    public Date getFechaHoraSalida() {
        return this.fechaHoraSalida;
    }

    public void setFechaHoraSalida(Date fechaHoraSalida) {
        this.fechaHoraSalida = fechaHoraSalida;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_hora_llegada", length = 29)
    public Date getFechaHoraLlegada() {
        return this.fechaHoraLlegada;
    }

    public void setFechaHoraLlegada(Date fechaHoraLlegada) {
        this.fechaHoraLlegada = fechaHoraLlegada;
    }

    @Column(name = "estado", length = 25)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "precio_economica", precision = 7)
    public BigDecimal getPrecioEconomica() {
        return this.precioEconomica;
    }

    public void setPrecioEconomica(BigDecimal precioEconomica) {
        this.precioEconomica = precioEconomica;
    }

    @Column(name = "precio_ejecutiva", precision = 7)
    public BigDecimal getPrecioEjecutiva() {
        return this.precioEjecutiva;
    }

    public void setPrecioEjecutiva(BigDecimal precioEjecutiva) {
        this.precioEjecutiva = precioEjecutiva;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "vuelo_tripulante", schema = "public", joinColumns = {
        @JoinColumn(name = "id_vuelo", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "id_tripulante", nullable = false, updatable = false)})
    public List<Tripulante> getTripulantes() {
        return this.tripulantes;
    }

    public void setTripulantes(List<Tripulante> tripulantes) {
        this.tripulantes = tripulantes;
    }

    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "vuelo")
    public List<VueloPasajero> getVueloPasajeros() {
        return this.vueloPasajeros;
    }

    public void setVueloPasajeros(List<VueloPasajero> vueloPasajeros) {
        this.vueloPasajeros = vueloPasajeros;
    }
}
